services:
  - type: web
    name: artenuvem
    env: python
    plan: free
    buildCommand: cd arte_nuvem && pip install -r requirements.txt
    startCommand: cd arte_nuvem && gunicorn app:app
    autoDeploy: true
